// SPDX-FileCopyrightText: Copyright 2026 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

#include "common/logging/classes.h"

namespace Common::Log {

std::string_view NameOf(Class log_class) {
    switch (log_class) {
    case Class::Log:
        return "Log";
    case Class::Common:
        return "Common";
    case Class::Common_Filesystem:
        return "Common.Filesystem";
    case Class::Common_Memory:
        return "Common.Memory";
    case Class::KeyManager:
        return "KeyManager";
    case Class::Core:
        return "Core";
    case Class::Core_Linker:
        return "Core.Linker";
    case Class::Core_Devices:
        return "Core.Devices";
    case Class::Config:
        return "Config";
    case Class::Debug:
        return "Debug";
    case Class::Kernel:
        return "Kernel";
    case Class::Kernel_Pthread:
        return "Kernel.Pthread";
    case Class::Kernel_Fs:
        return "Kernel.Fs";
    case Class::Kernel_Vmm:
        return "Kernel.Vmm";
    case Class::Kernel_Event:
        return "Kernel.Event";
    case Class::Kernel_Sce:
        return "Kernel.Sce";
    case Class::Lib:
        return "Lib";
    case Class::Lib_LibcInternal:
        return "Lib.LibcInternal";
    case Class::Lib_Kernel:
        return "Lib.Kernel";
    case Class::Lib_Pad:
        return "Lib.Pad";
    case Class::Lib_SystemGesture:
        return "Lib.SystemGesture";
    case Class::Lib_GnmDriver:
        return "Lib.GnmDriver";
    case Class::Lib_SystemService:
        return "Lib.SystemService";
    case Class::Lib_UserService:
        return "Lib.UserService";
    case Class::Lib_VideoOut:
        return "Lib.VideoOut";
    case Class::Lib_CommonDlg:
        return "Lib.CommonDlg";
    case Class::Lib_MsgDlg:
        return "Lib.MsgDlg";
    case Class::Lib_AudioOut:
        return "Lib.AudioOut";
    case Class::Lib_AudioIn:
        return "Lib.AudioIn";
    case Class::Lib_Move:
        return "Lib.Move";
    case Class::Lib_Net:
        return "Lib.Net";
    case Class::Lib_NetCtl:
        return "Lib.NetCtl";
    case Class::Lib_SaveData:
        return "Lib.SaveData";
    case Class::Lib_SaveDataDialog:
        return "Lib.SaveDataDialog";
    case Class::Lib_Ssl:
        return "Lib.Ssl";
    case Class::Lib_Ssl2:
        return "Lib.Ssl2";
    case Class::Lib_Http:
        return "Lib.Http";
    case Class::Lib_Http2:
        return "Lib.Http2";
    case Class::Lib_SysModule:
        return "Lib.SysModule";
    case Class::Lib_NpCommon:
        return "Lib.NpCommon";
    case Class::Lib_NpCommerce:
        return "Lib.NpCommerce";
    case Class::Lib_NpAuth:
        return "Lib.NpAuth";
    case Class::Lib_NpManager:
        return "Lib.NpManager";
    case Class::Lib_NpMatching2:
        return "Lib.NpMatching2";
    case Class::Lib_NpSignaling:
        return "Lib.NpSignaling";
    case Class::Lib_NpScore:
        return "Lib.NpScore";
    case Class::Lib_NpTrophy:
        return "Lib.NpTrophy";
    case Class::Lib_NpTus:
        return "Lib.NpTus";
    case Class::Lib_NpUtility:
        return "Lib.NpUtility";
    case Class::Lib_NpWebApi:
        return "Lib.NpWebApi";
    case Class::Lib_NpWebApi2:
        return "Lib.NpWebApi2";
    case Class::Lib_NpProfileDialog:
        return "Lib.NpProfileDialog";
    case Class::Lib_NpSnsFacebookDialog:
        return "Lib.NpSnsFacebookDialog";
    case Class::Lib_Screenshot:
        return "Lib.Screenshot";
    case Class::Lib_AppContent:
        return "Lib.AppContent";
    case Class::Lib_Rtc:
        return "Lib.Rtc";
    case Class::Lib_Rudp:
        return "Lib.Rudp";
    case Class::Lib_DiscMap:
        return "Lib.DiscMap";
    case Class::Lib_Png:
        return "Lib.Png";
    case Class::Lib_Jpeg:
        return "Lib.Jpeg";
    case Class::Lib_PlayGo:
        return "Lib.PlayGo";
    case Class::Lib_PlayGoDialog:
        return "Lib.PlayGoDialog";
    case Class::Lib_Random:
        return "Lib.Random";
    case Class::Lib_Usbd:
        return "Lib.Usbd";
    case Class::Lib_Ajm:
        return "Lib.Ajm";
    case Class::Lib_ErrorDialog:
        return "Lib.ErrorDialog";
    case Class::Lib_ImeDialog:
        return "Lib.ImeDialog";
    case Class::Lib_InvitationDialog:
        return "Lib.InvitationDialog";
    case Class::Lib_AvPlayer:
        return "Lib.AvPlayer";
    case Class::Lib_Ngs2:
        return "Lib.Ngs2";
    case Class::Lib_Audio3d:
        return "Lib.Audio3d";
    case Class::Lib_Ime:
        return "Lib.Ime";
    case Class::Lib_GameLiveStreaming:
        return "Lib.GameLiveStreaming";
    case Class::Lib_Remoteplay:
        return "Lib.Remoteplay";
    case Class::Lib_SharePlay:
        return "Lib.SharePlay";
    case Class::Lib_Fiber:
        return "Lib.Fiber";
    case Class::Lib_Vdec2:
        return "Lib.Vdec2";
    case Class::Lib_Vdecsw:
        return "Lib.Vdecsw";
    case Class::Lib_Videodec:
        return "Lib.Videodec";
    case Class::Lib_VideoRecording:
        return "Lib.VideoRecording";
    case Class::Lib_Voice:
        return "Lib.Voice";
    case Class::Lib_RazorCpu:
        return "Lib.RazorCpu";
    case Class::Lib_Mouse:
        return "Lib.Mouse";
    case Class::Lib_WebBrowserDialog:
        return "Lib.WebBrowserDialog";
    case Class::Lib_NpParty:
        return "Lib.NpParty";
    case Class::Lib_NpPartner:
        return "Lib.NpPartner";
    case Class::Lib_Zlib:
        return "Lib.Zlib";
    case Class::Lib_Hmd:
        return "Lib.Hmd";
    case Class::Lib_HmdSetupDialog:
        return "Lib.HmdSetupDialog";
    case Class::Lib_SigninDialog:
        return "Lib.SigninDialog";
    case Class::Lib_Camera:
        return "Lib.Camera";
    case Class::Lib_CompanionHttpd:
        return "Lib.CompanionHttpd";
    case Class::Lib_CompanionUtil:
        return "Lib.CompanionUtil";
    case Class::Lib_ContentExport:
        return "Lib.ContentExport";
    case Class::Lib_VrTracker:
        return "Lib.VrTracker";
    case Class::Lib_Font:
        return "Lib.Font";
    case Class::Lib_FontFt:
        return "Lib.FontFt";
    case Class::Frontend:
        return "Frontend";
    case Class::NpHandler:
        return "NpHandler";
    case Class::Render:
        return "Render";
    case Class::Render_Vulkan:
        return "Render_Vulkan";
    case Class::Render_Recompiler:
        return "Render_Recompiler";
    case Class::ShadNet:
        return "ShadNet";
    case Class::ImGui:
        return "ImGui";
    case Class::Loader:
        return "Loader";
    case Class::Input:
        return "Input";
    case Class::Tty:
        return "Tty";
    case Class::Count:
        return "Count";
    }
    return "Unknown";
}

} // namespace Common::Log