// SPDX-FileCopyrightText: Copyright 2026 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

#include "common/logging/classes.h"

namespace Common::Log {

std::string_view NameOf(Class log_class) {
    switch (log_class) {
    case Class::Log:
        return "Log";
    case Class::Common:
        return "Common";
    case Class::Common_Filesystem:
        return "Common_Filesystem";
    case Class::Common_Memory:
        return "Common_Memory";
    case Class::KeyManager:
        return "KeyManager";
    case Class::Core:
        return "Core";
    case Class::Core_Linker:
        return "Core_Linker";
    case Class::Core_Devices:
        return "Core_Devices";
    case Class::Config:
        return "Config";
    case Class::Debug:
        return "Debug";
    case Class::Kernel:
        return "Kernel";
    case Class::Kernel_Pthread:
        return "Kernel_Pthread";
    case Class::Kernel_Fs:
        return "Kernel_Fs";
    case Class::Kernel_Vmm:
        return "Kernel_Vmm";
    case Class::Kernel_Event:
        return "Kernel_Event";
    case Class::Kernel_Sce:
        return "Kernel_Sce";
    case Class::Lib:
        return "Lib";
    case Class::Lib_LibcInternal:
        return "Lib_LibcInternal";
    case Class::Lib_Kernel:
        return "Lib_Kernel";
    case Class::Lib_Pad:
        return "Lib_Pad";
    case Class::Lib_SystemGesture:
        return "Lib_SystemGesture";
    case Class::Lib_GnmDriver:
        return "Lib_GnmDriver";
    case Class::Lib_SystemService:
        return "Lib_SystemService";
    case Class::Lib_UserService:
        return "Lib_UserService";
    case Class::Lib_VideoOut:
        return "Lib_VideoOut";
    case Class::Lib_CommonDlg:
        return "Lib_CommonDlg";
    case Class::Lib_MsgDlg:
        return "Lib_MsgDlg";
    case Class::Lib_AudioOut:
        return "Lib_AudioOut";
    case Class::Lib_AudioIn:
        return "Lib_AudioIn";
    case Class::Lib_Move:
        return "Lib_Move";
    case Class::Lib_Net:
        return "Lib_Net";
    case Class::Lib_NetCtl:
        return "Lib_NetCtl";
    case Class::Lib_SaveData:
        return "Lib_SaveData";
    case Class::Lib_SaveDataDialog:
        return "Lib_SaveDataDialog";
    case Class::Lib_Ssl:
        return "Lib_Ssl";
    case Class::Lib_Ssl2:
        return "Lib_Ssl2";
    case Class::Lib_Http:
        return "Lib_Http";
    case Class::Lib_Http2:
        return "Lib_Http2";
    case Class::Lib_SysModule:
        return "Lib_SysModule";
    case Class::Lib_NpCommon:
        return "Lib_NpCommon";
    case Class::Lib_NpCommerce:
        return "Lib_NpCommerce";
    case Class::Lib_NpAuth:
        return "Lib_NpAuth";
    case Class::Lib_NpManager:
        return "Lib_NpManager";
    case Class::Lib_NpMatching2:
        return "Lib_NpMatching2";
    case Class::Lib_NpSignaling:
        return "Lib_NpSignaling";
    case Class::Lib_NpScore:
        return "Lib_NpScore";
    case Class::Lib_NpTrophy:
        return "Lib_NpTrophy";
    case Class::Lib_NpTus:
        return "Lib_NpTus";
    case Class::Lib_NpUtility:
        return "Lib_NpUtility";
    case Class::Lib_NpWebApi:
        return "Lib_NpWebApi";
    case Class::Lib_NpWebApi2:
        return "Lib_NpWebApi2";
    case Class::Lib_NpProfileDialog:
        return "Lib_NpProfileDialog";
    case Class::Lib_NpSnsFacebookDialog:
        return "Lib_NpSnsFacebookDialog";
    case Class::Lib_Screenshot:
        return "Lib_Screenshot";
    case Class::Lib_AppContent:
        return "Lib_AppContent";
    case Class::Lib_Rtc:
        return "Lib_Rtc";
    case Class::Lib_Rudp:
        return "Lib_Rudp";
    case Class::Lib_DiscMap:
        return "Lib_DiscMap";
    case Class::Lib_Png:
        return "Lib_Png";
    case Class::Lib_Jpeg:
        return "Lib_Jpeg";
    case Class::Lib_PlayGo:
        return "Lib_PlayGo";
    case Class::Lib_PlayGoDialog:
        return "Lib_PlayGoDialog";
    case Class::Lib_Random:
        return "Lib_Random";
    case Class::Lib_Usbd:
        return "Lib_Usbd";
    case Class::Lib_Ajm:
        return "Lib_Ajm";
    case Class::Lib_ErrorDialog:
        return "Lib_ErrorDialog";
    case Class::Lib_ImeDialog:
        return "Lib_ImeDialog";
    case Class::Lib_InvitationDialog:
        return "Lib_InvitationDialog";
    case Class::Lib_AvPlayer:
        return "Lib_AvPlayer";
    case Class::Lib_Ngs2:
        return "Lib_Ngs2";
    case Class::Lib_Audio3d:
        return "Lib_Audio3d";
    case Class::Lib_Ime:
        return "Lib_Ime";
    case Class::Lib_GameLiveStreaming:
        return "Lib_GameLiveStreaming";
    case Class::Lib_Remoteplay:
        return "Lib_Remoteplay";
    case Class::Lib_SharePlay:
        return "Lib_SharePlay";
    case Class::Lib_Fiber:
        return "Lib_Fiber";
    case Class::Lib_Vdec2:
        return "Lib_Vdec2";
    case Class::Lib_Vdecsw:
        return "Lib_Vdecsw";
    case Class::Lib_Videodec:
        return "Lib_Videodec";
    case Class::Lib_VideoRecording:
        return "Lib_VideoRecording";
    case Class::Lib_Voice:
        return "Lib_Voice";
    case Class::Lib_RazorCpu:
        return "Lib_RazorCpu";
    case Class::Lib_Mouse:
        return "Lib_Mouse";
    case Class::Lib_WebBrowserDialog:
        return "Lib_WebBrowserDialog";
    case Class::Lib_NpParty:
        return "Lib_NpParty";
    case Class::Lib_NpPartner:
        return "Lib_NpPartner";
    case Class::Lib_Zlib:
        return "Lib_Zlib";
    case Class::Lib_Hmd:
        return "Lib_Hmd";
    case Class::Lib_HmdSetupDialog:
        return "Lib_HmdSetupDialog";
    case Class::Lib_SigninDialog:
        return "Lib_SigninDialog";
    case Class::Lib_Camera:
        return "Lib_Camera";
    case Class::Lib_CompanionHttpd:
        return "Lib_CompanionHttpd";
    case Class::Lib_CompanionUtil:
        return "Lib_CompanionUtil";
    case Class::Lib_ContentExport:
        return "Lib_ContentExport";
    case Class::Lib_VrTracker:
        return "Lib_VrTracker";
    case Class::Lib_Font:
        return "Lib_Font";
    case Class::Lib_FontFt:
        return "Lib_FontFt";
    case Class::Frontend:
        return "Frontend";
    case Class::NpHandler:
        return "NpHandler";
    case Class::Render:
        return "Render";
    case Class::Render_Vulkan:
        return "Render_Vulkan";
    case Class::Render_Recompiler:
        return "Render_Recompiler";
    case Class::ShadNet:
        return "ShadNet";
    case Class::ImGui:
        return "ImGui";
    case Class::Loader:
        return "Loader";
    case Class::Input:
        return "Input";
    case Class::Tty:
        return "Tty";
    case Class::Count:
        return "Count";
    }
    return "Unknown";
}

} // namespace Common::Log