// SPDX-FileCopyrightText: Copyright 2024 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated By moduleGenerator
#include "libscevideoout.h"
#include "common/log.h"
#include "error_codes.h"

namespace Libraries::VideoOut{

int PS4_SYSV_ABI sceDbgVideoOutAddOutputModeVr60Privilege()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceDbgVideoOutAddProcessAttribute()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceDbgVideoOutRemoveProcessAttribute()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAddBufferAnisoPrivilege()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_87DE0FA368680D98()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAddBuffer()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAddBuffer4k2kPrivilege()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAddBufferYccPrivilege()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAddDisplayPositionEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAddDriver()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAddFlipEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAddPreVblankStartEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAddS3dHmdPrivilege()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAddSetModeEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAddStereoBuffer()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAddVblankEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAdjustColor_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutClose()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutColorSettingsSetGamma_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutConfigureOptionsInitialize_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutConfigureOutputMode_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutConfigureOutputModeEx_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutConfigureOutputModeExSubmitDoneUnsafe_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutControlHdcpEncryption()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutCursorDisable()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutCursorEnable()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutCursorIsUpdatePending()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutCursorSet2xMagnify()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutCursorSetHotSpot()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutCursorSetImageAddress()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutCursorSetPosition()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutCursorSetPositionStereo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutCurveSamplePointsCalc_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDeleteDisplayPositionEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDeleteDriver()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDeleteFlipEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDeletePreVblankStartEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDeleteSetModeEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDeleteVblankEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDriverAddEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDriverDecrementBufferLabel()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDriverDeleteEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDriverGetBufferLabelAddress()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDriverGetEopHandle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDriverGetFinishedEopHandle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDriverGetLatestEopHandle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDriverIncrementBufferLabel()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDriverResetBufferLabel()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutDriverTriggerEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetBufferInformation()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetBufferLabelAddress()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetCoredumpOutputMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetCurrentOutputMode_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetDeviceCapabilityInfo_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetDeviceInfoEx_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetDeviceInfoExOts_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetEventCount()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetEventData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetEventId()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetFlipStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetHdmiKsvList_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetHdmiMonitorInfo_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetHdmiMonitorInfoNoMask_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetPortStatusInfo_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetPortStatusInfoByBusSpecifier_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetResolutionStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetStatusForWebcore()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetVblankStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetVideoOutModeByBusSpecifier_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutHdmiMonitorInfoIsSupportedHdcpVersion_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutHdmiMonitorInfoIsSupportedVideoOutMode_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutIsFlipPending()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutLockBuffer()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutModeSetAny_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutOpen()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutRazorAddCallback()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutRazorRecallCallbacks()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutRazorRemoveCallback()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutRegisterBufferAttribute()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutRegisterBuffers()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutRegisterStereoBuffers()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutRemoveBuffer()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSetBlankAfterResume()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSetBufferAttribute()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSetDisplayEventPosition()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSetFlipRate()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSetGamutMetadata_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSetToneMap_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSetWindowModeMargins()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSubmitChangeBufferAttribute()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSubmitEopFlip()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSubmitFlip()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysAddSetModeEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysAddVblankEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysClose()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysConfigureOutputMode_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysCursorDisable()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysCursorEnable()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysCursorIsUpdatePending()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysCursorObtain()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysCursorRelease()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysCursorSetPosition()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysDeleteVblankEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysGetColorConversionStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysGetCurrentOutputMode_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysGetDeviceCapabilityInfoByBusSpecifier_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysGetFlipStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysGetMonitorInfo_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysGetPortStatusInfo_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysGetPortStatusInfoByBusSpecifier_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysGetResolutionStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysGetVblankStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysIsSupportedByMonitorInfo_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysReadCrc()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysReadCrc64()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysResetAtGpuReset()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysResetZoomBuffers()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysSetBlackLevel()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysSetDcePipeMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysSetDimmer()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysSetDisplayParameters()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysSetHdrScopeCallbacks()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysSetInvertedColors()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysSetOutputCsc()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysSetOverscanRatio()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysSetRedirectFlip()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysSetZoomBuffers()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysSubmitSubWindowLayout()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysUpdateDisplayParameter_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysUpdatePrivilege()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysUpdateRenderingMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutSysUpdateScalerParameters()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutUnlockBuffer()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutUnregisterBufferAttribute()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutUnregisterBuffers()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutWaitVblank()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_124ED74010241580()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_2438D6A18553BDD9()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_3389533D3C6878DD()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_3F96B7D8EBA56509()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_94C92412FE1A6876()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_A17AE74B11648BE7()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_BD73297BB32EADF7()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_C0A269161093AD7D()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_C192387E6509325C()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_FF9008114F7ED758()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAdjustColor2_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutGetHdmiRawEdid_()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceVideoOutAddBufferHdrPrivilege()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_DF1AD257C5341EC8()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

void RegisterlibSceVideoOut(Core::Loader::SymbolsResolver * sym) {
 LIB_FUNCTION("v+CRSpiQyVM", "libSceDbgVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceDbgVideoOutAddOutputModeVr60Privilege );
 LIB_FUNCTION("0eZpG16I-Ps", "libSceDbgVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceDbgVideoOutAddProcessAttribute );
 LIB_FUNCTION("gI9jbGyrJZo", "libSceDbgVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceDbgVideoOutRemoveProcessAttribute );
 LIB_FUNCTION("lm+1oyWKwy0", "libSceVideoOutAniso" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAddBufferAnisoPrivilege );
 LIB_FUNCTION("h94Po2hoDZg", "libSceDbgVideoOutSub4k" , 1 , "libSceVideoOut", 0, 0 , Func_87DE0FA368680D98 );
 LIB_FUNCTION("4iy9hG9Du1s", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAddBuffer );
 LIB_FUNCTION("twrSaoZ9cJs", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAddBuffer4k2kPrivilege );
 LIB_FUNCTION("D3s8DoEnuR4", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAddBufferYccPrivilege );
 LIB_FUNCTION("Cxb2w82t7lw", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAddDisplayPositionEvent );
 LIB_FUNCTION("HtwSd4H2Tws", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAddDriver );
 LIB_FUNCTION("HXzjK9yI30k", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAddFlipEvent );
 LIB_FUNCTION("keipklF0pMY", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAddPreVblankStartEvent );
 LIB_FUNCTION("iT+aFczA7ak", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAddS3dHmdPrivilege );
 LIB_FUNCTION("AjtlFa2HRws", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAddSetModeEvent );
 LIB_FUNCTION("Ax1Qs3Cm95Q", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAddStereoBuffer );
 LIB_FUNCTION("Xru92wHJRmg", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAddVblankEvent );
 LIB_FUNCTION("pv9CI5VC+R0", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAdjustColor_ );
 LIB_FUNCTION("uquVH4-Du78", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutClose );
 LIB_FUNCTION("DYhhWbJSeRg", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutColorSettingsSetGamma_ );
 LIB_FUNCTION("ktP9j1fN-zE", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutConfigureOptionsInitialize_ );
 LIB_FUNCTION("N1bEoJ4SRw4", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutConfigureOutputMode_ );
 LIB_FUNCTION("lQh55Q8DUAg", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutConfigureOutputModeEx_ );
 LIB_FUNCTION("-gYpMonpw2M", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutConfigureOutputModeExSubmitDoneUnsafe_ );
 LIB_FUNCTION("M-JkRj7X+No", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutControlHdcpEncryption );
 LIB_FUNCTION("fEPEwROdCwM", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutCursorDisable );
 LIB_FUNCTION("UPZWCH8qTM4", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutCursorEnable );
 LIB_FUNCTION("HibOtezzT6M", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutCursorIsUpdatePending );
 LIB_FUNCTION("Se-Zs6koGzk", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutCursorSet2xMagnify );
 LIB_FUNCTION("jr52f45OlWg", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutCursorSetHotSpot );
 LIB_FUNCTION("u-9bhWQApq8", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutCursorSetImageAddress );
 LIB_FUNCTION("N17AK88NdD0", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutCursorSetPosition );
 LIB_FUNCTION("735GfVO9v2s", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutCursorSetPositionStereo );
 LIB_FUNCTION("kazBRXPqR7c", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutCurveSamplePointsCalc_ );
 LIB_FUNCTION("gbJ8QxXOR6g", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDeleteDisplayPositionEvent );
 LIB_FUNCTION("KA515kD5rAY", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDeleteDriver );
 LIB_FUNCTION("-Ozn0F1AFRg", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDeleteFlipEvent );
 LIB_FUNCTION("elWQ9vERF-Q", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDeletePreVblankStartEvent );
 LIB_FUNCTION("fXCSkDTpJFg", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDeleteSetModeEvent );
 LIB_FUNCTION("oNOQn3knW6s", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDeleteVblankEvent );
 LIB_FUNCTION("oeNtdmvV4II", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDriverAddEvent );
 LIB_FUNCTION("0jGJbNTpSV4", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDriverDecrementBufferLabel );
 LIB_FUNCTION("lOR+Nos+Je8", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDriverDeleteEvent );
 LIB_FUNCTION("NGyEl5aT4fc", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDriverGetBufferLabelAddress );
 LIB_FUNCTION("P1bIHoga4jE", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDriverGetEopHandle );
 LIB_FUNCTION("G6peSSDP4iA", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDriverGetFinishedEopHandle );
 LIB_FUNCTION("GL8+3RHW5vk", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDriverGetLatestEopHandle );
 LIB_FUNCTION("Ztx4b2LhRDk", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDriverIncrementBufferLabel );
 LIB_FUNCTION("soAIjspgdt8", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDriverResetBufferLabel );
 LIB_FUNCTION("OHnnkrUcShM", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutDriverTriggerEvent );
 LIB_FUNCTION("5V8YGx9g0UA", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetBufferInformation );
 LIB_FUNCTION("OcQybQejHEY", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetBufferLabelAddress );
 LIB_FUNCTION("IZw2TINic+0", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetCoredumpOutputMode );
 LIB_FUNCTION("W0iQAbGaTBg", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetCurrentOutputMode_ );
 LIB_FUNCTION("kGVLc3htQE8", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetDeviceCapabilityInfo_ );
 LIB_FUNCTION("k6JLQGuPEYA", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetDeviceInfoEx_ );
 LIB_FUNCTION("p7FV-mU6EM0", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetDeviceInfoExOts_ );
 LIB_FUNCTION("Mt4QHHkxkOc", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetEventCount );
 LIB_FUNCTION("rWUTcKdkUzQ", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetEventData );
 LIB_FUNCTION("U2JJtSqNKZI", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetEventId );
 LIB_FUNCTION("SbU3dwp80lQ", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetFlipStatus );
 LIB_FUNCTION("hZvzQy2VLKY", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetHdmiKsvList_ );
 LIB_FUNCTION("+XlDnumvLVA", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetHdmiMonitorInfo_ );
 LIB_FUNCTION("421cr+-5Mus", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetHdmiMonitorInfoNoMask_ );
 LIB_FUNCTION("SDoPm73tOyI", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetPortStatusInfo_ );
 LIB_FUNCTION("4TPW3H2f-lM", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetPortStatusInfoByBusSpecifier_ );
 LIB_FUNCTION("6kPnj51T62Y", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetResolutionStatus );
 LIB_FUNCTION("+tB28CUr9W0", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetStatusForWebcore );
 LIB_FUNCTION("1FZBKy8HeNU", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetVblankStatus );
 LIB_FUNCTION("UazrNFzZPRU", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetVideoOutModeByBusSpecifier_ );
 LIB_FUNCTION("KCijjig3lGo", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutHdmiMonitorInfoIsSupportedHdcpVersion_ );
 LIB_FUNCTION("WBZrUaQY+EU", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutHdmiMonitorInfoIsSupportedVideoOutMode_ );
 LIB_FUNCTION("zgXifHT9ErY", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutIsFlipPending );
 LIB_FUNCTION("7ifZFxWJ9Q4", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutLockBuffer );
 LIB_FUNCTION("pjkDsgxli6c", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutModeSetAny_ );
 LIB_FUNCTION("Up36PTk687E", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutOpen );
 LIB_FUNCTION("ZX7C79uOujU", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutRazorAddCallback );
 LIB_FUNCTION("hGcTks-qqIU", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutRazorRecallCallbacks );
 LIB_FUNCTION("zUDW7kIFclI", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutRazorRemoveCallback );
 LIB_FUNCTION("EJQifjOp8s4", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutRegisterBufferAttribute );
 LIB_FUNCTION("w3BY+tAEiQY", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutRegisterBuffers );
 LIB_FUNCTION("lCTCOogRbk0", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutRegisterStereoBuffers );
 LIB_FUNCTION("H8teLntGkWs", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutRemoveBuffer );
 LIB_FUNCTION("zILy8t+5bPo", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSetBlankAfterResume );
 LIB_FUNCTION("i6-sR91Wt-4", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSetBufferAttribute );
 LIB_FUNCTION("18NPivA-byc", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSetDisplayEventPosition );
 LIB_FUNCTION("CBiu4mCE1DA", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSetFlipRate );
 LIB_FUNCTION("emayD9LHYsc", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSetGamutMetadata_ );
 LIB_FUNCTION("CxUz3nU06NE", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSetToneMap_ );
 LIB_FUNCTION("MTxxrOCeSig", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSetWindowModeMargins );
 LIB_FUNCTION("IOdgHlCGU-k", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSubmitChangeBufferAttribute );
 LIB_FUNCTION("j8xl+92A0q4", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSubmitEopFlip );
 LIB_FUNCTION("U46NwOiJpys", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSubmitFlip );
 LIB_FUNCTION("X8FN-5Nk-yE", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysAddSetModeEvent );
 LIB_FUNCTION("Ek+VR4lcJQI", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysAddVblankEvent );
 LIB_FUNCTION("dIb9LsrpkQM", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysClose );
 LIB_FUNCTION("rBDEhJgMruY", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysConfigureOutputMode_ );
 LIB_FUNCTION("6L0-A5piudQ", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysCursorDisable );
 LIB_FUNCTION("xwhyGPZkW6w", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysCursorEnable );
 LIB_FUNCTION("ekwMB-Ftq18", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysCursorIsUpdatePending );
 LIB_FUNCTION("+epU+rgObyw", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysCursorObtain );
 LIB_FUNCTION("QSmT3attiVg", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysCursorRelease );
 LIB_FUNCTION("fZgBeiGqE+c", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysCursorSetPosition );
 LIB_FUNCTION("iwsJdAZCg34", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysDeleteVblankEvent );
 LIB_FUNCTION("IpMhRnVgJUU", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysGetColorConversionStatus );
 LIB_FUNCTION("lXHMAc9Xjzo", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysGetCurrentOutputMode_ );
 LIB_FUNCTION("PYcZNLAIBnU", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysGetDeviceCapabilityInfoByBusSpecifier_ );
 LIB_FUNCTION("21sS8EU45cw", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysGetFlipStatus );
 LIB_FUNCTION("vMLWuJckGv0", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysGetMonitorInfo_ );
 LIB_FUNCTION("1OUW163iM+4", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysGetPortStatusInfo_ );
 LIB_FUNCTION("hmBBh-IJSzk", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysGetPortStatusInfoByBusSpecifier_ );
 LIB_FUNCTION("8XGijEoThE0", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysGetResolutionStatus );
 LIB_FUNCTION("d1AjT2uZJn0", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysGetVblankStatus );
 LIB_FUNCTION("mfxElr79O7Q", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysIsSupportedByMonitorInfo_ );
 LIB_FUNCTION("E8C608-pFng", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysReadCrc );
 LIB_FUNCTION("eBvoaLwfBBQ", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysReadCrc64 );
 LIB_FUNCTION("djc8fOzOXxk", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysResetAtGpuReset );
 LIB_FUNCTION("H9FTtSJuK3Y", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysResetZoomBuffers );
 LIB_FUNCTION("2KW9VnPMWDQ", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysSetBlackLevel );
 LIB_FUNCTION("jvPer4hz+UU", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysSetDcePipeMode );
 LIB_FUNCTION("OOF0YO73GTA", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysSetDimmer );
 LIB_FUNCTION("FZoCQTL8R04", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysSetDisplayParameters );
 LIB_FUNCTION("-2WA7vdSzbI", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysSetHdrScopeCallbacks );
 LIB_FUNCTION("w4inP0fKuDI", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysSetInvertedColors );
 LIB_FUNCTION("+lbk8RnyvmE", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysSetOutputCsc );
 LIB_FUNCTION("nMbAqI1ty8w", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysSetOverscanRatio );
 LIB_FUNCTION("e7pSAhCNrro", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysSetRedirectFlip );
 LIB_FUNCTION("fX9k++TzuQk", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysSetZoomBuffers );
 LIB_FUNCTION("dJo43e1jVoM", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysSubmitSubWindowLayout );
 LIB_FUNCTION("dtmPxxVErK0", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysUpdateDisplayParameter_ );
 LIB_FUNCTION("Jl91AhxKc0w", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysUpdatePrivilege );
 LIB_FUNCTION("4G37EIMMD+Q", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysUpdateRenderingMode );
 LIB_FUNCTION("XjqmNLGyLOg", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutSysUpdateScalerParameters );
 LIB_FUNCTION("amghnA-Ev5s", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutUnlockBuffer );
 LIB_FUNCTION("SRQSpP4QK5U", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutUnregisterBufferAttribute );
 LIB_FUNCTION("N5KDtkIjjJ4", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutUnregisterBuffers );
 LIB_FUNCTION("j6RaAUlaLv0", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutWaitVblank );
 LIB_FUNCTION("Ek7XQBAkFYA", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , Func_124ED74010241580 );
 LIB_FUNCTION("JDjWoYVTvdk", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , Func_2438D6A18553BDD9 );
 LIB_FUNCTION("M4lTPTxoeN0", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , Func_3389533D3C6878DD );
 LIB_FUNCTION("P5a32OulZQk", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , Func_3F96B7D8EBA56509 );
 LIB_FUNCTION("lMkkEv4aaHY", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , Func_94C92412FE1A6876 );
 LIB_FUNCTION("oXrnSxFki+c", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , Func_A17AE74B11648BE7 );
 LIB_FUNCTION("vXMpe7Murfc", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , Func_BD73297BB32EADF7 );
 LIB_FUNCTION("wKJpFhCTrX0", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , Func_C0A269161093AD7D );
 LIB_FUNCTION("wZI4fmUJMlw", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , Func_C192387E6509325C );
 LIB_FUNCTION("-5AIEU9+11g", "libSceVideoOut" , 1 , "libSceVideoOut", 0, 0 , Func_FF9008114F7ED758 );
 LIB_FUNCTION("twrSaoZ9cJs", "libSceVideoOutBaseMode4k" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAddBuffer4k2kPrivilege );
 LIB_FUNCTION("8Lf4Fp1TxA0", "libSceVideoOutExtra" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAdjustColor2_ );
 LIB_FUNCTION("+sXvR1JH9Aw", "libSceVideoOutRawEdid" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutGetHdmiRawEdid_ );
 LIB_FUNCTION("VAlir52gpQI", "libSceVideoOutHdr" , 1 , "libSceVideoOut", 0, 0 , sceVideoOutAddBufferHdrPrivilege );
 LIB_FUNCTION("3xrSV8U0Hsg", "libSceVideoOutWindow2Pre400" , 1 , "libSceVideoOut", 0, 0 , Func_DF1AD257C5341EC8 );
};

}