// SPDX-FileCopyrightText: Copyright 2024 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated By moduleGenerator
#include "libscegnmdriver.h"
#include "common/log.h"
#include "error_codes.h"

namespace Libraries::GnmDriver{

int PS4_SYSV_ABI sceGnmAddEqEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmAreSubmitsAllowed()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmBeginWorkload()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmComputeWaitOnAddress()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmComputeWaitSemaphore()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmCreateWorkloadStream()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerGetAddressWatch()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerHaltWavefront()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerReadGds()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerReadSqIndirectRegister()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerResumeWavefront()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerResumeWavefrontCreation()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerSetAddressWatch()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerWriteGds()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerWriteSqIndirectRegister()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebugHardwareStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDeleteEqEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDestroyWorkloadStream()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDingDong()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDingDongForWorkload()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDisableMipStatsReport()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDispatchDirect()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDispatchIndirect()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDispatchIndirectOnMec()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDispatchInitDefaultHardwareState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndex()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndexAuto()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndexIndirect()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndexIndirectCountMulti()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndexIndirectMulti()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndexMultiInstanced()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndexOffset()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndirect()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndirectCountMulti()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndirectMulti()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitDefaultHardwareState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitDefaultHardwareState175()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitDefaultHardwareState200()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitDefaultHardwareState350()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitToDefaultContextState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitToDefaultContextState400()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawOpaqueAuto()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverCaptureInProgress()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalRetrieveGnmInterface()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalRetrieveGnmInterfaceForGpuDebugger()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalRetrieveGnmInterfaceForGpuException()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalRetrieveGnmInterfaceForHDRScopes()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalRetrieveGnmInterfaceForReplay()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalRetrieveGnmInterfaceForResourceRegistration()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalRetrieveGnmInterfaceForValidation()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalVirtualQuery()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverTraceInProgress()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverTriggerCapture()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmEndWorkload()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmFindResourcesPublic()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmFlushGarlic()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetCoredumpAddress()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetCoredumpMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetCoredumpProtectionFaultTimestamp()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetDbgGcHandle()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetDebugTimestamp()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetEqEventType()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetEqTimeStamp()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetGpuBlockStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetGpuCoreClockFrequency()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetGpuInfoStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetLastWaitedAddress()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetNumTcaUnits()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetOffChipTessellationBufferSize()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetOwnerName()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetPhysicalCounterFromVirtualized()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetProtectionFaultTimeStamp()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetResourceBaseAddressAndSizeInBytes()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetResourceName()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetResourceShaderGuid()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetResourceType()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetResourceUserData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetShaderProgramBaseAddress()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetShaderStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetTheTessellationFactorRingBufferBaseAddress()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGpuPaDebugEnter()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGpuPaDebugLeave()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertDingDongMarker()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertPopMarker()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertPushColorMarker()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertPushMarker()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertSetColorMarker()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertSetMarker()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertThreadTraceMarker()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertWaitFlipDone()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmIsCoredumpValid()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmIsUserPaEnabled()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmLogicalCuIndexToPhysicalCuIndex()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmLogicalCuMaskToPhysicalCuMask()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmLogicalTcaUnitToPhysical()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmMapComputeQueue()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmMapComputeQueueWithPriority()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmPaDisableFlipCallbacks()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmPaEnableFlipCallbacks()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmPaHeartbeat()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmQueryResourceRegistrationUserMemoryRequirements()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRaiseUserExceptionEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRegisterGdsResource()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRegisterGnmLiveCallbackConfig()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRegisterOwner()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRegisterResource()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRequestFlipAndSubmitDone()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRequestFlipAndSubmitDoneForWorkload()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRequestMipStatsReportAndReset()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmResetVgtControl()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaClose()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaConstFill()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaCopyLinear()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaCopyTiled()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaCopyWindow()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaFlush()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaGetMinCmdSize()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaOpen()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetCsShader()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetCsShaderWithModifier()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetEmbeddedPsShader()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetEmbeddedVsShader()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetEsShader()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetGsRingSizes()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetGsShader()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetHsShader()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetLsShader()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetPsShader()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetPsShader350()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetResourceRegistrationUserMemory()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetResourceUserData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetSpiEnableSqCounters()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetSpiEnableSqCountersForUnitInstance()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetupMipStatsReport()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetVgtControl()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetVsShader()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetWaveLimitMultiplier()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetWaveLimitMultipliers()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmEndSpm()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmInit()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmInit2()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmSetDelay()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmSetMuxRam()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmSetMuxRam2()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmSetSelectCounter()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmSetSpmSelects()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmSetSpmSelects2()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmStartSpm()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttFini()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttFinishTrace()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetBcInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetGpuClocks()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetHiWater()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetStatus()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetTraceCounter()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetTraceWptr()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetWrapCounts()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetWrapCounts2()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetWritebackLabels()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttInit()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSelectMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSelectTarget()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSelectTokens()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSetCuPerfMask()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSetDceEventWrite()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSetHiWater()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSetTraceBuffer2()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSetTraceBuffers()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSetUserData()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSetUserdataTimer()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttStartTrace()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttStopTrace()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSwitchTraceBuffer()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSwitchTraceBuffer2()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttWaitForEvent()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSubmitAndFlipCommandBuffers()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSubmitAndFlipCommandBuffersForWorkload()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSubmitCommandBuffers()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSubmitCommandBuffersForWorkload()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSubmitDone()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUnmapComputeQueue()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUnregisterAllResourcesForOwner()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUnregisterOwnerAndResources()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUnregisterResource()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUpdateGsShader()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUpdateHsShader()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUpdatePsShader()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUpdatePsShader350()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUpdateVsShader()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateCommandBuffers()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateDisableDiagnostics()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateDisableDiagnostics2()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateDispatchCommandBuffers()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateDrawCommandBuffers()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateGetDiagnosticInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateGetDiagnostics()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateGetVersion()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateOnSubmitEnabled()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateResetState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidationRegisterMemoryCheckCallback()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceRazorCaptureCommandBuffersOnlyImmediate()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceRazorCaptureCommandBuffersOnlySinceLastFlip()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceRazorCaptureImmediate()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceRazorCaptureSinceLastFlip()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceRazorIsLoaded()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_063D065A2D6359C3()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_0CABACAFB258429D()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_150CF336FC2E99A3()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_17CA687F9EE52D49()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_1870B89F759C6B45()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_26F9029EF68A955E()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_301E3DBBAB092DB0()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_30BAFE172AF17FEF()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_3E6A3E8203D95317()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_40FEEF0C6534C434()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_416B9079DE4CBACE()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_4774D83BB4DDBF9A()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_50678F1CCEEB9A00()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_54A2EC5FA4C62413()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_5A9C52C83138AE6B()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_5D22193A31EA1142()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_725A36DEBB60948D()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_8021A502FA61B9BB()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_9D002FE0FA40F0E6()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_9D297F36A7028B71()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_A2D7EC7A7BCF79B3()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_AA12A3CB8990854A()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_ADC8DDC005020BC6()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_B0A8688B679CB42D()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_B489020B5157A5FF()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_BADE7B4C199140DD()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_D1511B9DCFFB3DD9()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_D53446649B02E58E()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_D8B6E8E28E1EF0A3()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_D93D733A19DD7454()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_DE995443BC2A8317()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_DF6E9528150C23FF()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_ECB4C6BA41FE3350()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebugModuleReset()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebugReset()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_C4C328B7CF3B4171()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitToDefaultContextStateInternalCommand()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitToDefaultContextStateInternalSize()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmFindResources()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetResourceRegistrationBuffers()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRegisterOwnerForSystem()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_1C43886B16EE5530()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_81037019ECCD0E01()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_BFB41C057478F0BF()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_E51D44DB8151238C()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_F916890425496553()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

void RegisterlibSceGnmDriver(Core::Loader::SymbolsResolver * sym) {
 LIB_FUNCTION("b0xyllnVY-I", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmAddEqEvent );
 LIB_FUNCTION("b08AgtPlHPg", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmAreSubmitsAllowed );
 LIB_FUNCTION("ihxrbsoSKWc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmBeginWorkload );
 LIB_FUNCTION("ffrNQOshows", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmComputeWaitOnAddress );
 LIB_FUNCTION("EJapNl2+pgU", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmComputeWaitSemaphore );
 LIB_FUNCTION("5udAm+6boVg", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmCreateWorkloadStream );
 LIB_FUNCTION("jwCEzr7uEP4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDebuggerGetAddressWatch );
 LIB_FUNCTION("PNf0G7gvFHQ", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDebuggerHaltWavefront );
 LIB_FUNCTION("nO-tMnaxJiE", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDebuggerReadGds );
 LIB_FUNCTION("t0HIQWnvK9E", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDebuggerReadSqIndirectRegister );
 LIB_FUNCTION("HsLtF4jKe48", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDebuggerResumeWavefront );
 LIB_FUNCTION("JRKSSV0YzwA", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDebuggerResumeWavefrontCreation );
 LIB_FUNCTION("jpTMyYB8UBI", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDebuggerSetAddressWatch );
 LIB_FUNCTION("MJG69Q7ti+s", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDebuggerWriteGds );
 LIB_FUNCTION("PaFw9w6f808", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDebuggerWriteSqIndirectRegister );
 LIB_FUNCTION("qpGITzPE+Zc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDebugHardwareStatus );
 LIB_FUNCTION("PVT+fuoS9gU", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDeleteEqEvent );
 LIB_FUNCTION("UtObDRQiGbs", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDestroyWorkloadStream );
 LIB_FUNCTION("bX5IbRvECXk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDingDong );
 LIB_FUNCTION("byXlqupd8cE", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDingDongForWorkload );
 LIB_FUNCTION("HHo1BAljZO8", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDisableMipStatsReport );
 LIB_FUNCTION("0BzLGljcwBo", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDispatchDirect );
 LIB_FUNCTION("Z43vKp5k7r0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDispatchIndirect );
 LIB_FUNCTION("wED4ZXCFJT0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDispatchIndirectOnMec );
 LIB_FUNCTION("nF6bFRUBRAU", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDispatchInitDefaultHardwareState );
 LIB_FUNCTION("HlTPoZ-oY7Y", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawIndex );
 LIB_FUNCTION("GGsn7jMTxw4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawIndexAuto );
 LIB_FUNCTION("ED9-Fjr8Ta4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawIndexIndirect );
 LIB_FUNCTION("thbPcG7E7qk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawIndexIndirectCountMulti );
 LIB_FUNCTION("5q95ravnueg", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawIndexIndirectMulti );
 LIB_FUNCTION("jHdPvIzlpKc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawIndexMultiInstanced );
 LIB_FUNCTION("oYM+YzfCm2Y", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawIndexOffset );
 LIB_FUNCTION("4v+otIIdjqg", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawIndirect );
 LIB_FUNCTION("cUCo8OvArrw", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawIndirectCountMulti );
 LIB_FUNCTION("f5QQLp9rzGk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawIndirectMulti );
 LIB_FUNCTION("Idffwf3yh8s", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawInitDefaultHardwareState );
 LIB_FUNCTION("QhnyReteJ1M", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawInitDefaultHardwareState175 );
 LIB_FUNCTION("0H2vBYbTLHI", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawInitDefaultHardwareState200 );
 LIB_FUNCTION("yb2cRhagD1I", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawInitDefaultHardwareState350 );
 LIB_FUNCTION("8lH54sfjfmU", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawInitToDefaultContextState );
 LIB_FUNCTION("im2ZuItabu4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawInitToDefaultContextState400 );
 LIB_FUNCTION("stDSYW2SBVM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawOpaqueAuto );
 LIB_FUNCTION("TLV4mswiZ4A", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDriverCaptureInProgress );
 LIB_FUNCTION("ODEeJ1GfDtE", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDriverInternalRetrieveGnmInterface );
 LIB_FUNCTION("4LSXsEKPTsE", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDriverInternalRetrieveGnmInterfaceForGpuDebugger );
 LIB_FUNCTION("MpncRjHNYRE", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDriverInternalRetrieveGnmInterfaceForGpuException );
 LIB_FUNCTION("EwjWGcIOgeM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDriverInternalRetrieveGnmInterfaceForHDRScopes );
 LIB_FUNCTION("3EXdrVC7WFk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDriverInternalRetrieveGnmInterfaceForReplay );
 LIB_FUNCTION("P9iKqxAGeck", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDriverInternalRetrieveGnmInterfaceForResourceRegistration );
 LIB_FUNCTION("t-vIc5cTEzg", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDriverInternalRetrieveGnmInterfaceForValidation );
 LIB_FUNCTION("BvvO8Up88Zc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDriverInternalVirtualQuery );
 LIB_FUNCTION("R6z1xM3pW-w", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDriverTraceInProgress );
 LIB_FUNCTION("d88anrgNoKY", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDriverTriggerCapture );
 LIB_FUNCTION("Fa3x75OOLRA", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmEndWorkload );
 LIB_FUNCTION("4Mv9OXypBG8", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmFindResourcesPublic );
 LIB_FUNCTION("iBt3Oe00Kvc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmFlushGarlic );
 LIB_FUNCTION("GviyYfFQIkc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetCoredumpAddress );
 LIB_FUNCTION("meiO-5ZCVIE", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetCoredumpMode );
 LIB_FUNCTION("O-7nHKgcNSQ", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetCoredumpProtectionFaultTimestamp );
 LIB_FUNCTION("bSJFzejYrJI", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetDbgGcHandle );
 LIB_FUNCTION("pd4C7da6sEg", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetDebugTimestamp );
 LIB_FUNCTION("UoYY0DWMC0U", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetEqEventType );
 LIB_FUNCTION("H7-fgvEutM0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetEqTimeStamp );
 LIB_FUNCTION("oL4hGI1PMpw", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetGpuBlockStatus );
 LIB_FUNCTION("Fwvh++m9IQI", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetGpuCoreClockFrequency );
 LIB_FUNCTION("tZCSL5ulnB4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetGpuInfoStatus );
 LIB_FUNCTION("iFirFzgYsvw", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetLastWaitedAddress );
 LIB_FUNCTION("KnldROUkWJY", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetNumTcaUnits );
 LIB_FUNCTION("FFVZcCu3zWU", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetOffChipTessellationBufferSize );
 LIB_FUNCTION("QJjPjlmPAL0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetOwnerName );
 LIB_FUNCTION("dewXw5roLs0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetPhysicalCounterFromVirtualized );
 LIB_FUNCTION("fzJdEihTFV4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetProtectionFaultTimeStamp );
 LIB_FUNCTION("4PKnYXOhcx4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetResourceBaseAddressAndSizeInBytes );
 LIB_FUNCTION("O0S96YnD04U", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetResourceName );
 LIB_FUNCTION("UBv7FkVfzcQ", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetResourceShaderGuid );
 LIB_FUNCTION("bdqdvIkLPIU", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetResourceType );
 LIB_FUNCTION("UoBuWAhKk7U", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetResourceUserData );
 LIB_FUNCTION("nEyFbYUloIM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetShaderProgramBaseAddress );
 LIB_FUNCTION("k7iGTvDQPLQ", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetShaderStatus );
 LIB_FUNCTION("ln33zjBrfjk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetTheTessellationFactorRingBufferBaseAddress );
 LIB_FUNCTION("QLdG7G-PBZo", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGpuPaDebugEnter );
 LIB_FUNCTION("tVEdZe3wlbY", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGpuPaDebugLeave );
 LIB_FUNCTION("NfvOrNzy6sk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmInsertDingDongMarker );
 LIB_FUNCTION("7qZVNgEu+SY", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmInsertPopMarker );
 LIB_FUNCTION("aPIZJTXC+cU", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmInsertPushColorMarker );
 LIB_FUNCTION("W1Etj-jlW7Y", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmInsertPushMarker );
 LIB_FUNCTION("aj3L-iaFmyk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmInsertSetColorMarker );
 LIB_FUNCTION("jiItzS6+22g", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmInsertSetMarker );
 LIB_FUNCTION("URDgJcXhQOs", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmInsertThreadTraceMarker );
 LIB_FUNCTION("1qXLHIpROPE", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmInsertWaitFlipDone );
 LIB_FUNCTION("HRyNHoAjb6E", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmIsCoredumpValid );
 LIB_FUNCTION("jg33rEKLfVs", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmIsUserPaEnabled );
 LIB_FUNCTION("26PM5Mzl8zc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmLogicalCuIndexToPhysicalCuIndex );
 LIB_FUNCTION("RU74kek-N0c", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmLogicalCuMaskToPhysicalCuMask );
 LIB_FUNCTION("Kl0Z3LH07QI", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmLogicalTcaUnitToPhysical );
 LIB_FUNCTION("29oKvKXzEZo", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmMapComputeQueue );
 LIB_FUNCTION("A+uGq+3KFtQ", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmMapComputeQueueWithPriority );
 LIB_FUNCTION("+N+wrSYBLIw", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmPaDisableFlipCallbacks );
 LIB_FUNCTION("8WDA9RiXLaw", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmPaEnableFlipCallbacks );
 LIB_FUNCTION("tNuT48mApTc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmPaHeartbeat );
 LIB_FUNCTION("6IMbpR7nTzA", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmQueryResourceRegistrationUserMemoryRequirements );
 LIB_FUNCTION("+rJnw2e9O+0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmRaiseUserExceptionEvent );
 LIB_FUNCTION("9Mv61HaMhfA", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmRegisterGdsResource );
 LIB_FUNCTION("t7-VbMosbR4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmRegisterGnmLiveCallbackConfig );
 LIB_FUNCTION("ZFqKFl23aMc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmRegisterOwner );
 LIB_FUNCTION("nvEwfYAImTs", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmRegisterResource );
 LIB_FUNCTION("gObODli-OH8", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmRequestFlipAndSubmitDone );
 LIB_FUNCTION("6YRHhh5mHCs", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmRequestFlipAndSubmitDoneForWorkload );
 LIB_FUNCTION("f85orjx7qts", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmRequestMipStatsReportAndReset );
 LIB_FUNCTION("MYRtYhojKdA", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmResetVgtControl );
 LIB_FUNCTION("hS0MKPRdNr0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSdmaClose );
 LIB_FUNCTION("31G6PB2oRYQ", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSdmaConstFill );
 LIB_FUNCTION("Lg2isla2XeQ", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSdmaCopyLinear );
 LIB_FUNCTION("-Se2FY+UTsI", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSdmaCopyTiled );
 LIB_FUNCTION("OlFgKnBsALE", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSdmaCopyWindow );
 LIB_FUNCTION("LQQN0SwQv8c", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSdmaFlush );
 LIB_FUNCTION("suUlSjWr7CE", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSdmaGetMinCmdSize );
 LIB_FUNCTION("5AtqyMgO7fM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSdmaOpen );
 LIB_FUNCTION("KXltnCwEJHQ", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetCsShader );
 LIB_FUNCTION("Kx-h-nWQJ8A", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetCsShaderWithModifier );
 LIB_FUNCTION("X9Omw9dwv5M", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetEmbeddedPsShader );
 LIB_FUNCTION("+AFvOEXrKJk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetEmbeddedVsShader );
 LIB_FUNCTION("FUHG8sQ3R58", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetEsShader );
 LIB_FUNCTION("jtkqXpAOY6w", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetGsRingSizes );
 LIB_FUNCTION("UJwNuMBcUAk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetGsShader );
 LIB_FUNCTION("VJNjFtqiF5w", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetHsShader );
 LIB_FUNCTION("vckdzbQ46SI", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetLsShader );
 LIB_FUNCTION("bQVd5YzCal0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetPsShader );
 LIB_FUNCTION("5uFKckiJYRM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetPsShader350 );
 LIB_FUNCTION("q-qhDxP67Hg", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetResourceRegistrationUserMemory );
 LIB_FUNCTION("K3BKBBYKUSE", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetResourceUserData );
 LIB_FUNCTION("0O3xxFaiObw", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetSpiEnableSqCounters );
 LIB_FUNCTION("lN7Gk-p9u78", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetSpiEnableSqCountersForUnitInstance );
 LIB_FUNCTION("+xuDhxlWRPg", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetupMipStatsReport );
 LIB_FUNCTION("cFCp0NX8wf0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetVgtControl );
 LIB_FUNCTION("gAhCn6UiU4Y", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetVsShader );
 LIB_FUNCTION("y+iI2lkX+qI", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetWaveLimitMultiplier );
 LIB_FUNCTION("XiyzNZ9J4nQ", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSetWaveLimitMultipliers );
 LIB_FUNCTION("kkn+iy-mhyg", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSpmEndSpm );
 LIB_FUNCTION("aqhuK2Mj4X4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSpmInit );
 LIB_FUNCTION("KHpZ9hJo1c0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSpmInit2 );
 LIB_FUNCTION("QEsMC+M3yjE", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSpmSetDelay );
 LIB_FUNCTION("hljMAxTLNF0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSpmSetMuxRam );
 LIB_FUNCTION("bioGsp74SLM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSpmSetMuxRam2 );
 LIB_FUNCTION("cMWWYeqQQlM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSpmSetSelectCounter );
 LIB_FUNCTION("-zJi8Vb4Du4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSpmSetSpmSelects );
 LIB_FUNCTION("xTsOqp-1bE4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSpmSetSpmSelects2 );
 LIB_FUNCTION("AmmYLcJGTl0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSpmStartSpm );
 LIB_FUNCTION("UHDiSFDxNao", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttFini );
 LIB_FUNCTION("a3tLC56vwug", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttFinishTrace );
 LIB_FUNCTION("L-owl1dSKKg", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttGetBcInfo );
 LIB_FUNCTION("LQtzqghKQm4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttGetGpuClocks );
 LIB_FUNCTION("wYN5mmv6Ya8", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttGetHiWater );
 LIB_FUNCTION("9X4SkENMS0M", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttGetStatus );
 LIB_FUNCTION("lbMccQM2iqc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttGetTraceCounter );
 LIB_FUNCTION("DYAC6JUeZvM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttGetTraceWptr );
 LIB_FUNCTION("pS2tjBxzJr4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttGetWrapCounts );
 LIB_FUNCTION("rXV8az6X+fM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttGetWrapCounts2 );
 LIB_FUNCTION("ARS+TNLopyk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttGetWritebackLabels );
 LIB_FUNCTION("X6yCBYPP7HA", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttInit );
 LIB_FUNCTION("2IJhUyK8moE", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttSelectMode );
 LIB_FUNCTION("QA5h6Gh3r60", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttSelectTarget );
 LIB_FUNCTION("F5XJY1XHa3Y", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttSelectTokens );
 LIB_FUNCTION("wJtaTpNZfH4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttSetCuPerfMask );
 LIB_FUNCTION("kY4dsQh+SH4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttSetDceEventWrite );
 LIB_FUNCTION("7XRH1CIfNpI", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttSetHiWater );
 LIB_FUNCTION("05YzC2r3hHo", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttSetTraceBuffer2 );
 LIB_FUNCTION("ASUric-2EnI", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttSetTraceBuffers );
 LIB_FUNCTION("gPxYzPp2wlo", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttSetUserData );
 LIB_FUNCTION("d-YcZX7SIQA", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttSetUserdataTimer );
 LIB_FUNCTION("ru8cb4he6O8", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttStartTrace );
 LIB_FUNCTION("gVuGo1nBnG8", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttStopTrace );
 LIB_FUNCTION("OpyolX6RwS0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttSwitchTraceBuffer );
 LIB_FUNCTION("dl5u5eGBgNk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttSwitchTraceBuffer2 );
 LIB_FUNCTION("QLzOwOF0t+A", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSqttWaitForEvent );
 LIB_FUNCTION("xbxNatawohc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSubmitAndFlipCommandBuffers );
 LIB_FUNCTION("Ga6r7H6Y0RI", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSubmitAndFlipCommandBuffersForWorkload );
 LIB_FUNCTION("zwY0YV91TTI", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSubmitCommandBuffers );
 LIB_FUNCTION("jRcI8VcgTz4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSubmitCommandBuffersForWorkload );
 LIB_FUNCTION("yvZ73uQUqrk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmSubmitDone );
 LIB_FUNCTION("ArSg-TGinhk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmUnmapComputeQueue );
 LIB_FUNCTION("yhFCnaz5daw", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmUnregisterAllResourcesForOwner );
 LIB_FUNCTION("fhKwCVVj9nk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmUnregisterOwnerAndResources );
 LIB_FUNCTION("k8EXkhIP+lM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmUnregisterResource );
 LIB_FUNCTION("nLM2i2+65hA", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmUpdateGsShader );
 LIB_FUNCTION("GNlx+y7xPdE", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmUpdateHsShader );
 LIB_FUNCTION("4MgRw-bVNQU", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmUpdatePsShader );
 LIB_FUNCTION("mLVL7N7BVBg", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmUpdatePsShader350 );
 LIB_FUNCTION("V31V01UiScY", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmUpdateVsShader );
 LIB_FUNCTION("iCO804ZgzdA", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmValidateCommandBuffers );
 LIB_FUNCTION("SXw4dZEkgpA", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmValidateDisableDiagnostics );
 LIB_FUNCTION("BgM3t3LvcNk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmValidateDisableDiagnostics2 );
 LIB_FUNCTION("qGP74T5OWJc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmValidateDispatchCommandBuffers );
 LIB_FUNCTION("hsZPf1lON7E", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmValidateDrawCommandBuffers );
 LIB_FUNCTION("RX7XCNSaL6I", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmValidateGetDiagnosticInfo );
 LIB_FUNCTION("5SHGNwLXBV4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmValidateGetDiagnostics );
 LIB_FUNCTION("HzMN7ANqYEc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmValidateGetVersion );
 LIB_FUNCTION("rTIV11nMQuM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmValidateOnSubmitEnabled );
 LIB_FUNCTION("MBMa6EFu4Ko", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmValidateResetState );
 LIB_FUNCTION("Q7t4VEYLafI", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceGnmValidationRegisterMemoryCheckCallback );
 LIB_FUNCTION("xeTLfxVIQO4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceRazorCaptureCommandBuffersOnlyImmediate );
 LIB_FUNCTION("9thMn+uB1is", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceRazorCaptureCommandBuffersOnlySinceLastFlip );
 LIB_FUNCTION("u9YKpRRHe-M", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceRazorCaptureImmediate );
 LIB_FUNCTION("4UFagYlfuAM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceRazorCaptureSinceLastFlip );
 LIB_FUNCTION("f33OrruQYbM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , sceRazorIsLoaded );
 LIB_FUNCTION("Bj0GWi1jWcM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_063D065A2D6359C3 );
 LIB_FUNCTION("DKusr7JYQp0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_0CABACAFB258429D );
 LIB_FUNCTION("FQzzNvwumaM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_150CF336FC2E99A3 );
 LIB_FUNCTION("F8pof57lLUk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_17CA687F9EE52D49 );
 LIB_FUNCTION("GHC4n3Wca0U", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_1870B89F759C6B45 );
 LIB_FUNCTION("JvkCnvaKlV4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_26F9029EF68A955E );
 LIB_FUNCTION("MB49u6sJLbA", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_301E3DBBAB092DB0 );
 LIB_FUNCTION("MLr+Fyrxf+8", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_30BAFE172AF17FEF );
 LIB_FUNCTION("Pmo+ggPZUxc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_3E6A3E8203D95317 );
 LIB_FUNCTION("QP7vDGU0xDQ", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_40FEEF0C6534C434 );
 LIB_FUNCTION("QWuQed5Mus4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_416B9079DE4CBACE );
 LIB_FUNCTION("R3TYO7Tdv5o", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_4774D83BB4DDBF9A );
 LIB_FUNCTION("UGePHM7rmgA", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_50678F1CCEEB9A00 );
 LIB_FUNCTION("VKLsX6TGJBM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_54A2EC5FA4C62413 );
 LIB_FUNCTION("WpxSyDE4rms", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_5A9C52C83138AE6B );
 LIB_FUNCTION("XSIZOjHqEUI", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_5D22193A31EA1142 );
 LIB_FUNCTION("clo23rtglI0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_725A36DEBB60948D );
 LIB_FUNCTION("gCGlAvphubs", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_8021A502FA61B9BB );
 LIB_FUNCTION("nQAv4PpA8OY", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_9D002FE0FA40F0E6 );
 LIB_FUNCTION("nSl-NqcCi3E", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_9D297F36A7028B71 );
 LIB_FUNCTION("otfsenvPebM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_A2D7EC7A7BCF79B3 );
 LIB_FUNCTION("qhKjy4mQhUo", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_AA12A3CB8990854A );
 LIB_FUNCTION("rcjdwAUCC8Y", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_ADC8DDC005020BC6 );
 LIB_FUNCTION("sKhoi2ectC0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_B0A8688B679CB42D );
 LIB_FUNCTION("tIkCC1FXpf8", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_B489020B5157A5FF );
 LIB_FUNCTION("ut57TBmRQN0", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_BADE7B4C199140DD );
 LIB_FUNCTION("0VEbnc-7Pdk", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_D1511B9DCFFB3DD9 );
 LIB_FUNCTION("1TRGZJsC5Y4", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_D53446649B02E58E );
 LIB_FUNCTION("2Lbo4o4e8KM", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_D8B6E8E28E1EF0A3 );
 LIB_FUNCTION("2T1zOhnddFQ", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_D93D733A19DD7454 );
 LIB_FUNCTION("3plUQ7wqgxc", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_DE995443BC2A8317 );
 LIB_FUNCTION("326VKBUMI-8", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_DF6E9528150C23FF );
 LIB_FUNCTION("7LTGukH+M1A", "libSceGnmDriver" , 1 , "libSceGnmDriver", 1, 1 , Func_ECB4C6BA41FE3350 );
 LIB_FUNCTION("dqPBvjFVpTA", "libSceGnmDebugModuleReset" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDebugModuleReset );
 LIB_FUNCTION("RNPAItiMLIg", "libSceGnmDebugReset" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDebugReset );
 LIB_FUNCTION("xMMot887QXE", "libSceGnmDebugReset" , 1 , "libSceGnmDriver", 1, 1 , Func_C4C328B7CF3B4171 );
 LIB_FUNCTION("pF1HQjbmQJ0", "libSceGnmDriverCompat" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawInitToDefaultContextStateInternalCommand );
 LIB_FUNCTION("jajhf-Gi3AI", "libSceGnmDriverCompat" , 1 , "libSceGnmDriver", 1, 1 , sceGnmDrawInitToDefaultContextStateInternalSize );
 LIB_FUNCTION("vbcR4Ken6AA", "libSceGnmDriverResourceRegistration" , 1 , "libSceGnmDriver", 1, 1 , sceGnmFindResources );
 LIB_FUNCTION("eLQbNsKeTkU", "libSceGnmDriverResourceRegistration" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetResourceRegistrationBuffers );
 LIB_FUNCTION("j6mSQs3UgaY", "libSceGnmDriverResourceRegistration" , 1 , "libSceGnmDriver", 1, 1 , sceGnmRegisterOwnerForSystem );
 LIB_FUNCTION("HEOIaxbuVTA", "libSceGnmDriverResourceRegistration" , 1 , "libSceGnmDriver", 1, 1 , Func_1C43886B16EE5530 );
 LIB_FUNCTION("gQNwGezNDgE", "libSceGnmDriverResourceRegistration" , 1 , "libSceGnmDriver", 1, 1 , Func_81037019ECCD0E01 );
 LIB_FUNCTION("v7QcBXR48L8", "libSceGnmDriverResourceRegistration" , 1 , "libSceGnmDriver", 1, 1 , Func_BFB41C057478F0BF );
 LIB_FUNCTION("5R1E24FRI4w", "libSceGnmDriverResourceRegistration" , 1 , "libSceGnmDriver", 1, 1 , Func_E51D44DB8151238C );
 LIB_FUNCTION("+RaJBCVJZVM", "libSceGnmDriverResourceRegistration" , 1 , "libSceGnmDriver", 1, 1 , Func_F916890425496553 );
 LIB_FUNCTION("Fwvh++m9IQI", "libSceGnmGetGpuCoreClockFrequency" , 1 , "libSceGnmDriver", 1, 1 , sceGnmGetGpuCoreClockFrequency );
 LIB_FUNCTION("R3TYO7Tdv5o", "libSceGnmWaitFreeSubmit" , 1 , "libSceGnmDriver", 1, 1 , Func_4774D83BB4DDBF9A );
 LIB_FUNCTION("ut57TBmRQN0", "libSceGnmWaitFreeSubmit" , 1 , "libSceGnmDriver", 1, 1 , Func_BADE7B4C199140DD );
};

}