// SPDX-FileCopyrightText: Copyright 2024 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated By moduleGenerator
#include "libsceaudioout.h"
#include "common/log.h"
#include "error_codes.h"

namespace Libraries::AudioOut{

int PS4_SYSV_ABI sceAudioOutDeviceIdOpen()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioDeviceControlGet()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioDeviceControlSet()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutA3dControl()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutA3dExit()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutA3dInit()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutAttachToApplicationByPid()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutChangeAppModuleState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutClose()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutDetachFromApplicationByPid()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutExConfigureOutputMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutExGetSystemInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutExPtClose()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutExPtGetLastOutputTime()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutExPtOpen()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutExSystemInfoIsSupportedAudioOutExMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutGetFocusEnablePid()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutGetHandleStatusInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutGetInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutGetInfoOpenNum()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutGetLastOutputTime()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutGetPortState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutGetSimulatedBusUsableStatusByBusType()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutGetSimulatedHandleStatusInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutGetSimulatedHandleStatusInfo2()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutGetSparkVss()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutGetSystemState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutInit()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutInitIpmiGetSession()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutMasteringGetState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutMasteringInit()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutMasteringSetParam()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutMasteringTerm()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutMbusInit()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutOpen()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutOpenEx()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutOutput()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutOutputs()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutPtClose()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutPtGetLastOutputTime()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutPtOpen()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetConnections()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetConnectionsForUser()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetDevConnection()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetHeadphoneOutMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetJediJackVolume()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetJediSpkVolume()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetMainOutput()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetMixLevelPadSpk()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetMorpheusParam()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetMorpheusWorkingMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetPortConnections()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetPortStatuses()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetRecMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetSparkParam()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetUsbVolume()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetVolume()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetVolumeDown()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutStartAuxBroadcast()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutStartSharePlay()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutStopAuxBroadcast()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutStopSharePlay()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSuspendResume()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSysConfigureOutputMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSysGetHdmiMonitorInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSysGetSystemInfo()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSysHdmiMonitorInfoIsSupportedAudioOutMode()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSystemControlGet()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSystemControlSet()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSparkControlSetEqCoef()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceAudioOutSetSystemDebugState()
{
	PRINT_UNIMPLEMENTED_FUNCTION_NAME();
	return ORBIS_OK;
}

void RegisterlibSceAudioOut(Core::Loader::SymbolsResolver * sym) {
 LIB_FUNCTION("cx2dYFbzIAg", "libSceAudioOutDeviceService" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutDeviceIdOpen );
 LIB_FUNCTION("tKumjQSzhys", "libSceAudioDeviceControl" , 1 , "libSceAudioOut", 1, 1 , sceAudioDeviceControlGet );
 LIB_FUNCTION("5ChfcHOf3SM", "libSceAudioDeviceControl" , 1 , "libSceAudioOut", 1, 1 , sceAudioDeviceControlSet );
 LIB_FUNCTION("Iz9X7ISldhs", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutA3dControl );
 LIB_FUNCTION("9RVIoocOVAo", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutA3dExit );
 LIB_FUNCTION("n7KgxE8rOuE", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutA3dInit );
 LIB_FUNCTION("WBAO6-n0-4M", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutAttachToApplicationByPid );
 LIB_FUNCTION("O3FM2WXIJaI", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutChangeAppModuleState );
 LIB_FUNCTION("s1--uE9mBFw", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutClose );
 LIB_FUNCTION("ol4LbeTG8mc", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutDetachFromApplicationByPid );
 LIB_FUNCTION("r1V9IFEE+Ts", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutExConfigureOutputMode );
 LIB_FUNCTION("wZakRQsWGos", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutExGetSystemInfo );
 LIB_FUNCTION("xjjhT5uw08o", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutExPtClose );
 LIB_FUNCTION("DsST7TNsyfo", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutExPtGetLastOutputTime );
 LIB_FUNCTION("4UlW3CSuCa4", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutExPtOpen );
 LIB_FUNCTION("Xcj8VTtnZw0", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutExSystemInfoIsSupportedAudioOutExMode );
 LIB_FUNCTION("I3Fwcmkg5Po", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutGetFocusEnablePid );
 LIB_FUNCTION("Y3lXfCFEWFY", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutGetHandleStatusInfo );
 LIB_FUNCTION("-00OAutAw+c", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutGetInfo );
 LIB_FUNCTION("RqmKxBqB8B4", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutGetInfoOpenNum );
 LIB_FUNCTION("Ptlts326pds", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutGetLastOutputTime );
 LIB_FUNCTION("GrQ9s4IrNaQ", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutGetPortState );
 LIB_FUNCTION("c7mVozxJkPU", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutGetSimulatedBusUsableStatusByBusType );
 LIB_FUNCTION("pWmS7LajYlo", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutGetSimulatedHandleStatusInfo );
 LIB_FUNCTION("oPLghhAWgMM", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutGetSimulatedHandleStatusInfo2 );
 LIB_FUNCTION("5+r7JYHpkXg", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutGetSparkVss );
 LIB_FUNCTION("R5hemoKKID8", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutGetSystemState );
 LIB_FUNCTION("JfEPXVxhFqA", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutInit );
 LIB_FUNCTION("n16Kdoxnvl0", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutInitIpmiGetSession );
 LIB_FUNCTION("r+qKw+ueD+Q", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutMasteringGetState );
 LIB_FUNCTION("xX4RLegarbg", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutMasteringInit );
 LIB_FUNCTION("4055yaUg3EY", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutMasteringSetParam );
 LIB_FUNCTION("RVWtUgoif5o", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutMasteringTerm );
 LIB_FUNCTION("-LXhcGARw3k", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutMbusInit );
 LIB_FUNCTION("ekNvsT22rsY", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutOpen );
 LIB_FUNCTION("qLpSK75lXI4", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutOpenEx );
 LIB_FUNCTION("QOQtbeDqsT4", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutOutput );
 LIB_FUNCTION("w3PdaSTSwGE", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutOutputs );
 LIB_FUNCTION("MapHTgeogbk", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutPtClose );
 LIB_FUNCTION("YZaq+UKbriQ", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutPtGetLastOutputTime );
 LIB_FUNCTION("xyT8IUCL3CI", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutPtOpen );
 LIB_FUNCTION("o4OLQQqqA90", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetConnections );
 LIB_FUNCTION("QHq2ylFOZ0k", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetConnectionsForUser );
 LIB_FUNCTION("r9KGqGpwTpg", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetDevConnection );
 LIB_FUNCTION("08MKi2E-RcE", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetHeadphoneOutMode );
 LIB_FUNCTION("18IVGrIQDU4", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetJediJackVolume );
 LIB_FUNCTION("h0o+D4YYr1k", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetJediSpkVolume );
 LIB_FUNCTION("KI9cl22to7E", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetMainOutput );
 LIB_FUNCTION("wVwPU50pS1c", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetMixLevelPadSpk );
 LIB_FUNCTION("eeRsbeGYe20", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetMorpheusParam );
 LIB_FUNCTION("IZrItPnflBM", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetMorpheusWorkingMode );
 LIB_FUNCTION("Gy0ReOgXW00", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetPortConnections );
 LIB_FUNCTION("oRBFflIrCg0", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetPortStatuses );
 LIB_FUNCTION("ae-IVPMSWjU", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetRecMode );
 LIB_FUNCTION("d3WL2uPE1eE", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetSparkParam );
 LIB_FUNCTION("X7Cfsiujm8Y", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetUsbVolume );
 LIB_FUNCTION("b+uAV89IlxE", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetVolume );
 LIB_FUNCTION("rho9DH-0ehs", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetVolumeDown );
 LIB_FUNCTION("I91P0HAPpjw", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutStartAuxBroadcast );
 LIB_FUNCTION("uo+eoPzdQ-s", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutStartSharePlay );
 LIB_FUNCTION("AImiaYFrKdc", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutStopAuxBroadcast );
 LIB_FUNCTION("teCyKKZPjME", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutStopSharePlay );
 LIB_FUNCTION("95bdtHdNUic", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSuspendResume );
 LIB_FUNCTION("oRJZnXxok-M", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSysConfigureOutputMode );
 LIB_FUNCTION("Tf9-yOJwF-A", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSysGetHdmiMonitorInfo );
 LIB_FUNCTION("y2-hP-KoTMI", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSysGetSystemInfo );
 LIB_FUNCTION("YV+bnMvMfYg", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSysHdmiMonitorInfoIsSupportedAudioOutMode );
 LIB_FUNCTION("JEHhANREcLs", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSystemControlGet );
 LIB_FUNCTION("9CHWVv6r3Dg", "libSceAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSystemControlSet );
 LIB_FUNCTION("Mt7JB3lOyJk", "libSceAudioOutSparkControl" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSparkControlSetEqCoef );
 LIB_FUNCTION("7UsdDOEvjlk", "libSceDbgAudioOut" , 1 , "libSceAudioOut", 1, 1 , sceAudioOutSetSystemDebugState );
};

}