// SPDX-FileCopyrightText: Copyright 2024 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

constexpr int ORBIS_RUDP_ERROR_NOT_INITIALIZED = 0x80770001;
constexpr int ORBIS_RUDP_ERROR_INVALID_ARGUMENT = 0x80770004;
constexpr int ORBIS_RUDP_ERROR_INVALID_CONTEXT_ID = 0x80770003;
constexpr int ORBIS_RUDP_ERROR_INVALID_POLL_ID = 0x8077001f;
constexpr int ORBIS_RUDP_ERROR_TOO_MANY_CONTEXTS = 0;
constexpr int ORBIS_RUDP_ERROR_CANCELLED = 0x80770014;
constexpr int ORBIS_RUDP_ERROR_ALREADY_INITIALIZED = 0x80770002;
constexpr int ORBIS_RUDP_ERROR_MEMORY = 0x80770007;
constexpr int ORBIS_RUDP_ERROR_NOT_ACCEPTABLE = 0x80770011;
constexpr int ORBIS_RUDP_ERROR_THREAD_IN_USE = 0;
constexpr int ORBIS_RUDP_ERROR_THREAD = 0;
constexpr int ORBIS_RUDP_ERROR_INVALID_SOCKET = 0;
constexpr int ORBIS_RUDP_ERROR_NO_EVENT_HANDLER = 0;
constexpr int ORBIS_RUDP_ERROR_INVALID_MUXMODE = 0;
constexpr int ORBIS_RUDP_ERROR_INVALID_VPORT = 0;
constexpr int ORBIS_RUDP_ERROR_VPORT_EXHAUSTED = 0;
constexpr int ORBIS_RUDP_ERROR_CONN_TIMEOUT = 0;
constexpr int ORBIS_RUDP_ERROR_NOT_BOUND = 0;
constexpr int ORBIS_RUDP_ERROR_ADDR_IN_USE = 0;
constexpr int ORBIS_RUDP_ERROR_IN_PROGRESS = 0;
constexpr int ORBIS_RUDP_ERROR_WOULDBLOCK = 0;
constexpr int ORBIS_RUDP_ERROR_MSG_TOO_LARGE = 0;
constexpr int ORBIS_RUDP_ERROR_BUFFER_TOO_SMALL = 0;
constexpr int ORBIS_RUDP_ERROR_END_OF_DATA = 0;
constexpr int ORBIS_RUDP_ERROR_MSG_MALFORMED = 0;
constexpr int ORBIS_RUDP_ERROR_INVALID_OPTION = 0;