// SPDX-FileCopyrightText: Copyright 2024-2026 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated By moduleGenerator
#include "common/logging/log.h"
#include "core/libraries/error_codes.h"
#include "core/libraries/libs.h"
#include "signindialog.h"

namespace Libraries::SigninDialog {

static bool g_lib_init = false;
static bool g_lib_open = false;

s32 PS4_SYSV_ABI sceSigninDialogInitialize() {
    LOG_ERROR(Lib_SigninDialog, "(STUBBED) called");
    g_lib_init = true;
    return ORBIS_OK;
}

s32 PS4_SYSV_ABI sceSigninDialogOpen() {
    LOG_ERROR(Lib_SigninDialog, "(STUBBED) called");
    g_lib_open = true;
    return ORBIS_OK;
}

Status PS4_SYSV_ABI sceSigninDialogGetStatus() {
    if (!g_lib_init) {
        return Status::NONE;
    }
    if (!g_lib_open) {
        return Status::NONE;
    }
    LOG_ERROR(Lib_SigninDialog, "(STUBBED) called, return 'finished' status");
    return Status::FINISHED;
}

Status PS4_SYSV_ABI sceSigninDialogUpdateStatus() {
    if (!g_lib_init) {
        return Status::NONE;
    }
    if (!g_lib_open) {
        return Status::NONE;
    }
    LOG_ERROR(Lib_SigninDialog, "(STUBBED) called, return 'finished' status");
    return g_lib_open ? Status::FINISHED : Status::NONE;
}

s32 PS4_SYSV_ABI sceSigninDialogGetResult(OrbisSigninDialogResult* result) {
    if (!g_lib_init) {
        return ORBIS_SIGNIN_DIALOG_ERROR_NOT_INITIALIZED;
    }
    LOG_ERROR(Lib_SigninDialog, "(STUBBED) called");
    if (!result) {
        return ORBIS_SIGNIN_DIALOG_ERROR_PARAM_INVALID;
    }
    result->result = OrbisSigninDialogResultType::OK;
    return ORBIS_OK;
}

s32 PS4_SYSV_ABI sceSigninDialogClose() {
    LOG_ERROR(Lib_SigninDialog, "(STUBBED) called");
    g_lib_open = false;
    return ORBIS_OK;
}

s32 PS4_SYSV_ABI sceSigninDialogTerminate() {
    LOG_ERROR(Lib_SigninDialog, "(STUBBED) called");
    g_lib_open = false;
    g_lib_init = false;
    return ORBIS_OK;
}

void RegisterLib(Core::Loader::SymbolsResolver* sym) {
    LIB_FUNCTION("mlYGfmqE3fQ", "libSceSigninDialog", 1, "libSceSigninDialog",
                 sceSigninDialogInitialize);
    LIB_FUNCTION("JlpJVoRWv7U", "libSceSigninDialog", 1, "libSceSigninDialog", sceSigninDialogOpen);
    LIB_FUNCTION("2m077aeC+PA", "libSceSigninDialog", 1, "libSceSigninDialog",
                 sceSigninDialogGetStatus);
    LIB_FUNCTION("Bw31liTFT3A", "libSceSigninDialog", 1, "libSceSigninDialog",
                 sceSigninDialogUpdateStatus);
    LIB_FUNCTION("nqG7rqnYw1U", "libSceSigninDialog", 1, "libSceSigninDialog",
                 sceSigninDialogGetResult);
    LIB_FUNCTION("M3OkENHcyiU", "libSceSigninDialog", 1, "libSceSigninDialog",
                 sceSigninDialogClose);
    LIB_FUNCTION("LXlmS6PvJdU", "libSceSigninDialog", 1, "libSceSigninDialog",
                 sceSigninDialogTerminate);
};

} // namespace Libraries::SigninDialog
